### ISSUE TITLE
Không vào được trang chủ download

### ISSUE THREAD

**Issue by schizoid09** [huyphan/NAKL#29]
Bạn ơi mình rất thích bộ gõ của bạn, giờ vừa mua máy mới muốn dùng nữa nhưng vào zepvn.com thì toàn bị 404 not found (redirect godaddy)

**Comment by huyphan** [comment]
Hi @schizoid09, cảm ơn bạn đã thông báo lỗi. Mình đã renew lại domain name, bạn sẽ vào lại được trang download trong khoảng tối đa 4 giờ nữa.
