### ISSUE TITLE
Cám ơn về một bộ gõ rất tuyệt vời

### ISSUE THREAD

**Issue by luong-komorebi** [huyphan/NAKL#31]
Mình mở issue vì không tìm được email hay kênh xã hội nào để nói lời cám ơn này. Bộ gõ của bạn đã giúp mình rất nhiều và mình cực thích vì nó được open source.
Hi vọng bạn có thể nhúng 1 đường link hoặc một nút donate nào đó trong phần tùy chọn để những ai trân trong công sức của bạn có thể đóng góp.

**Comment by huyphan** [comment]
Hi @LewisVo, cảm ơn bạn đã ủng hộ bộ gõ. NAKL được phát hành dạng mã mở vì mình muốn khuyến khích cộng đồng cùng đóng góp tính năng cho bộ gõ.

Trên [trang chủ của NAKL](http://zepvn.com/NAKL/) có đường link cho donation thông qua Paypal. 100% số tiền đóng góp sẽ được chuyển cho các tổ chức từ thiện.
