### ISSUE TITLE
Chức năng gõ tắt không hoạt động trên MAC 10.14 Mojave

### ISSUE THREAD

**Issue by hoangnamitc** [huyphan/NAKL#37]
Xin chào, 

Hiện chức năng gõ tắt trên MacOS Mojave không hoạt động. 

Xin cảm ơn!

**Comment by notrealdev** [comment]
Repo này chắc drop rồi, 2 năm ko thấy cập nhật...

**Comment by hoangnamitc** [comment]
Mới thấy đăng trên tinhte nên xài thử mà thấy phím tắt không hoạt động, mà repo này lâu quá không thấy update. chắc drop rồi :(

**Comment by huyphan** [comment]
Mình đang dùng Mojave và chức năng gõ tắt vẫn hoạt động bình thường. Bạn @hoangnamitc có thể cho mình biết các phím tắt và từ đầy đủ tương ứng mà bạn đang dùng không? 

Mình hiện tại không còn nhiều thời gian để phát triển thêm chức năng mới cho bộ gõ, tuy nhiên mình vẫn cập nhật và vá lỗi cho NAKL (nếu có).

**Comment by hoangnamitc** [comment]
Hi Huyphan,

tất cả từ gõ tắt của máy mình đều không hoạt động.
(vd: hcn -> hoangnamcode@gmail.com)
